apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsapp-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: newsapp-backend
  template:
    metadata:
      labels:
        app: newsapp-backend
    spec:
      containers:
        - name: newsapp
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: newsapp-config
            - secretRef:
                name: newsapp-secret
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: newsapp-config
