apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsapp-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: newsapp-frontend
  template:
    metadata:
      labels:
        app: newsapp-frontend
    spec:
      containers:
        - name: newsapp-ui
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 1234
