apiVersion: v1
kind: Service
metadata:
  name: newsapp-backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: newsapp-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: 8080