spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chandler032/news-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        encrypt:
          enabled: true
        decrypt:
          enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: * # Expose all actuator endpoints
          endpoint:
            health:
              show-details: always
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
      endpoint:
        health:
          probes:
            enabled: true

  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "1234567890123456"

server:
  port: 8071
